on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: check-link-rot

jobs:
  check-link-rot:
    uses: https://github.com/easystats/workflows/blob/main/.github/workflows/check-link-rot.yaml@master